version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=PONG.settings  # Change myproject to your project name
    ports:
      - "8000:8000"
